<?php

namespace Drupal\ample\Event;

use Symfony\Contracts\EventDispatcher\Event;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use RuntimeException;

class UserLoginEvent extends Event {

  public const NAME = 'ample.Forcepassword';
  /**
   * Constructs the object.
   *
   * @param \Drupal\user\UserInterface $account
   *   The Drupal account of the user logged in.
   */
  public function __construct(public UserInterface $account) {
   // \Drupal::logger('ample')->info("executed inside event");
    //session_start();
   // if(empty($_SESSION))
    //{
      //ch\Drupal::logger()->
    //}
    //session_commit();
    //$username = \Drupal::currentUser()->getAccountName();
    //\Drupal::messenger()->addMessage("username is");
    //\Drupal::messenger()->addMessage($username);
    try{
      \Drupal::logger("ample")->info("exception happended");
      $url = Url::fromUri("internal:/example");
      $path = $url->toString();
      $response = new RedirectResponse($path);
      $response->send();
    }
    catch(\Exception $e){
      $e->getMessage();
      \Drupal::logger("ample")->info("exception happended");
    }
    
      //$username = \Drupal::currentUser()->getAccountName();
      //\Drupal::messenger()->addMessage("username is");
      //\Drupal::messenger()->addMessage($username);
}
  
}
the above program runs and give following error


RuntimeException: Failed to start the session because headers have already been sent by "C:\xampp\htdocs\drupal\demos\vendor\symfony\http-foundation\Response.php" at line 1325. in Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (line 132 of C:\xampp\htdocs\drupal\demos\vendor\symfony\http-foundation\Session\Storage\NativeSessionStorage.php)
